export const scaleFactor = 4;

export const dialogueData = {
  pc: `Welcome to my digital domain! I'm a Data Analyst at the University of Connecticut (UConn), where I unravel the mysteries of complex data sets. With a passion for puzzle-solving, I approach big data as an intricate enigma waiting to be cracked. My tool of choice is Python, but I'm a programming polyglot at heart - as long as it's code, I'm in my element. When I'm not taming data, you can find me immersed in real-time strategy games like Age of Empires or Empire Earth, where I relish the thrill of building empires and outmaneuvering foes. The strategic thinking and problem-solving skills I hone in these games complement my data analysis work perfectly.`,
  "sofa-table": `Ah, my happy place! That's my sofa, where I unwind and let my imagination run wild. When I'm not busy solving data puzzles or gaming, you can find me cozied up here with a good book or a stack of comics. "The Hitchhiker's Guide to the Galaxy" by Douglas Adams is one of my all-time favorites. I'm also passionate about art, and I enjoy reading about everything from Renaissance masters to contemporary street artists. There's something about the creative process, the expression of ideas, and the emotional resonance of art that speaks to me on a deep level.`,
  tv: `Step into my entertainment zone! That's my trusty TV, the portal to endless adventures and laughter. When I'm not conquering data sets, you can find me binge-watching movies or indulging in the absurd humor of my beloved cartoon, SpongeBob SquarePants - who wouldn't love a sponge who lives in a pineapple under the sea? But the screen time doesn't stop there! I'm also an avid gamer, and my console is always warmed up for a few rounds of Madden, where I crush my friends with my legendary football skills, or Halo, where I save humanity from the Covenant's evil clutches. The thrill of competition and the rush of adrenaline are the perfect complements to my analytical mind.`,
  bed: `Welcome to my dream incubator! This is where I lay my head to rest, but also where my mind sparks with creativity. I often find myself conjuring up innovative solutions or ideas in the stillness of the night. Once an idea strikes, I'm consumed by it! I have to jot it down immediately, or risk losing sleep as my mental energy goes into overdrive. It's as if my brain is a dam, and the idea is the key that unlocks the floodgates of creativity.`,
  desk: `Welcome to my command center! This is my desk, where the magic happens, and my trusty resume is always within reach. Want to see what I'm working with? <a href="https://raw.githubusercontent.com/carlosgeovany/carlosgeovany.github.io/main/assets/docs/CarlosPerezResume.pdf" target="_blank">Download Resume?</a> And if you want to learn more about my skills, projects, and adventures, head over to my <a href="https://carlosgeovany.github.io" target="_blank">Website</a>. I'm always on the lookout for exciting new opportunities, so if you've got a challenging project or a cool job opening, let's connect! I'd love to chat about how we can collaborate and create something amazing together`,
  library: `My shelves are packed with a treasure trove of books, each one a portal to a new world of knowledge and adventure. I'm particularly fascinated by the fierce warriors and mystical gods of Viking lore and Norse mythology – there's something about the sagas and legends that speaks to my sense of wonder and awe. I devour books on classic art, reveling in the masterpieces of the past and the stories of the visionaries who created them. From the brushstrokes of the Renaissance to the bold experiments of modernism, art has a way of captivating my imagination and inspiring my own creativity. And then, of course, there's Sociology. My shelves are lined with books that help me make sense of our global community, from the classics of the discipline to cutting-edge research and theory.`,
  exit: `Thanks for dropping by my digital abode! It was great sharing my world with you. I hope you had as much fun exploring as I did showing you around. Until next time, stay curious, keep exploring, and I hope to see you soon! Don't be a stranger - come back and visit me again sometime!`,
  "cs-degree": `These are my Bachelor's degrees in Sociology and Information Technology Systems (ITS). They're the dynamic duo that arms me with a deep understanding of human behavior and the technical prowess to tackle complex problems. With Sociology, I gained a keen eye for social patterns, relationships, and the intricacies of human interaction. I learned to analyze, critique, and empathize – essential skills for navigating the complexities of our modern world. Meanwhile, my ITS degree gave me the technical expertise to harness the power of data, software, and systems. I developed a strong foundation in programming, networking, and problem-solving, allowing me to bridge the gap between people and technology. Together, these degrees form a powerful combination that fuels my passions for data analysis, puzzle-solving, and creative expression. They're the foundation upon which I build my skills, and the catalysts for my future endeavors.`,
  lisa:`Meet Lisa &#10084 my adorable pup! She's a bundle of energy, a ball of fur, and a heart of gold. I'm completely smitten with her playful pounces, snuggly cuddles, and loving gaze. She brings boundless joy to my world, and I'm so grateful to be her human.`,
};